// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.acme.presenter.domain;

import com.acme.presenter.domain.PresentationElement;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PresentationElement_Roo_Configurable {
    
    declare @type: PresentationElement: @Configurable;
    
}
